### PR TITLE
Fixed up for Kinetic / 16.04 + Gazebo7

### PR DESCRIPTION
**Pull request by lucbettaieb**
Wasn't compiling on 16.04 + Kinetic.  It works now, I promise!

### CODE REVIEW

**Comment by lucbettaieb** [comment]
@florianshkurti ping ping

**Comment by lucbettaieb** [comment]
@florianshkurti ;c

**Comment by florianshkurti** [comment]
Thank you!

**Comment by lucbettaieb** [comment]
@florianshkurti Of course!

**Pull request merged**
